<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>cffc475d-c3a2-443a-93a3-455046b2c79d</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    </ItemGroup>

</Project>
